---
###
# install-dependencies playbook
##
# Used by ./tads install-dependencies
##

- hosts: localhost
  tasks:
    - name: Install Vagrant and Virtualbox
      become: yes
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - virtualbox
        - vagrant

    - name: Install Terraform
      shell: >
          wget -O /tmp/terraform.zip "https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip"
          && unzip -d ~/.local/bin /tmp/terraform.zip
          && rm -f /tmp/terraform.zip
      environment:
        TERRAFORM_VERSION: 0.12.12
      args:
        creates: ~/.local/bin/terraform
        warn: False

- hosts: localhost
  tags:
    - dev_dependencies
  tasks:
    - name: Install ansible-lint
      become: True
      pip:
        name: ansible-lint

    - name: Install shellcheck
      become: True
      shell: >
          (wget -qO- "https://storage.googleapis.com/shellcheck/shellcheck-${SHELLCHECK_VERSION}.linux.x86_64.tar.xz" | tar -xJv --directory /tmp)
          && cp "/tmp/shellcheck-${SHELLCHECK_VERSION}/shellcheck" /usr/bin/
          && rm -rf /tmp/shellcheck-${SHELLCHECK_VERSION}
      environment:
        SHELLCHECK_VERSION: v0.6.0
      args:
        creates: /usr/bin/shellcheck
        warn: False
